---
title: "Analisis de datos ómicos"
author: 
- Alex Sánchez-Pla$^{1,2}$ y Ricardo Gonzalo Sanz$^2$
- $^1$ Departament de Genètica, Microbiologia i Estadística. Universitat de Barcelona (UB).
- $^2$ Unitat de Estadística i Bioinformàtica. Vall d'Hebron Institut de Recerca (VHIR).
site: bookdown::bookdown_site
documentclass: book
bibliography: MDAreview.bib
biblio-style: apalike
link-citations: yes
github-repo: https://github.com/ASPteaching/Analisis_de_datos_omicos-Materiales_para_un_curso
output:
  bookdown::gitbook: default
  bookdown::html_document2: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```


# Presentación

Este documento es una versión actualizada -en varios sentidos- de unos materiales de análisis de microarrays que escribimos allá por 2010, usando LateX y Sweave, junto con la profesora M. Carme Ruíz de Villa para la asignatura "Análisis de Microarrays" del posgrado de Bioinformática de la Universitat Oberta de Catalunya .

En estos años han cambiado muchas cosas. El posgrado es ahora un máster interuniversitario entre la UOC y la Universidad de Barcelona (UB). Muchos estadísticos y/o bioinformáticos -entre los que me incluyo- han cambiado de LateX/Sweave a RStudio/RMarkdown y Github. Mi compañera de escritura, Mamen, se ha jubilado, pero un nuevo compañero, Ricardo, se ha apuntado a la aventura de revivir estos materiales. Y aunque sigue sin estar claro si los microarrays también se jubilaran pronto, el campo de las ómicas ha crecido de forma explosiva. El "Análisis de datos ómicos", título de este nuevo documento ya no se centra en los microarrays. También trata de RNA-seq, Proteómica, Metagenómica, Metabolómica o Epigenómica por citar sólo algunos de los más populares.

Es obvio que un curso de "Análisis de datos ómicos" no puede abarcar todas estas disciplinas, aunque también lo es que comparten muchos elementos comunes.

El plan de desarrollo para esta nueva edición, que podrá seguirse en el repositorio de Github (), tendrá dos fases:

1. En una primera, actualizaremos la versión original a RMarkdown, eliminando aspectos desfasados y actualizando el código R a la versión actual de R/Bioconductor.
2. En una posterior miraré de añadir capítulos que introduzcan nuevas tecnologías y muestren como analizar los datos que estas generan. Si logro engañar a algunos colegas para que escriban un capítulo también los añadiré a los autores.

Previsiblemente este documento, con sus errores e imperfecciones se quedará como "open source" para uso de quien lo desee sin tener que pasar por el doloroso y anquilosante proceso de convertirlo en un libro, que, en este caso, empezaría a quedar obsoleto al minuto de estar acabado.

## Instalación de paquetes de R y código de los capítulos

En este documento se utiliza cierto número de paquetes de R. En vez de indicar que se instalen la primera vez que aparecen hemos creado un archivo de instalación -que convertiremos más adelante en un paquete- llamado `install_me_1st,R`. Nuestra recomendación es que antes de empezar a usar los materiales se ejecute dicho archivo para asegurarse de que todos los paquetes necesarios se encuentran instalados, preferentemente en la versión más actualizada. 

El archivo se encuentra en el directorio `codigo_R`.

Este directorio contiene además los archivos de código R extraídos de los archivos fuente "Rmarkdown" (con la instrucción `knitr::purl()`) para facilitar su ejecución.

